site_name: Online-Dokumentationen
theme: material
site_description: A Material Design theme for MkDocs
site_author: Meinolf Droste
site_url: http://mdwp-mkdocs-cms.netlify.com/

extra:
  social:
    - type: 'github'
      link: 'https://github.com/capriosa'
    - type: 'twitter'
      link: 'https://twitter.com/mdwp'
    - type: 'facebook'
      link: 'https://facebook.com/mdwp.de'
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: pink


extra_css:
  - 'stylesheets/extra.css'

repo_name: 'capriosa/mkdocs-cms'
repo_url: 'https://github.com/capriosa/mkdocs-cms'

# Copyright
copyright: '<a href="https://www.mdwp.de">mdwp</a>'

# Theme directory
theme_dir: material

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Page tree
pages:
  - 'MkDocs-CMS': 'index.md'
  - McDocs:
    -- 'Dokumentation': 'mkdocs.md'
  - Material Theme: 
    - 'Getting started': 'getting-started.md'
    - Erweiterungen:
      - 'Admonition': 'extensions/admonition.md'
      - 'CodeHilite': 'extensions/codehilite.md'
      - 'Footnotes': 'extensions/footnotes.md'
      - 'Metadata': 'extensions/metadata.md'
      - 'Permalinks': 'extensions/permalinks.md'
      - 'PyMdown': 'extensions/pymdown.md'
    - 'Specimen': 'specimen.md'
    - 'Customization': 'customization.md'
    - Lizenz:
      - 'Release notes': 'release-notes.md'
      - 'Contributing': 'contributing.md'
      - 'License': 'license.md'
  - 'M. Droste': 'mdroste.md'
  - 'Kontakt': 'kontakt.md'
  - 'Impressum': 'impressum.md'